package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import java.util.concurrent.TimeUnit;

public final class zzr<R extends Result> extends OptionalPendingResult<R> {
    private final zzb<R> zzaiy;

    public zzr(PendingResult<R> pendingResult) {
        if (!(pendingResult instanceof zzb)) {
            throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
        }
        this.zzaiy = (zzb) pendingResult;
    }

    public R await() {
        return this.zzaiy.await();
    }

    public R await(long j, TimeUnit timeUnit) {
        return this.zzaiy.await(j, timeUnit);
    }

    public void cancel() {
        this.zzaiy.cancel();
    }

    public R get() {
        if (isDone()) {
            return await(0, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }

    public boolean isCanceled() {
        return this.zzaiy.isCanceled();
    }

    public boolean isDone() {
        return this.zzaiy.isReady();
    }

    public void setResultCallback(ResultCallback<? super R> resultCallback) {
        this.zzaiy.setResultCallback(resultCallback);
    }

    public void setResultCallback(ResultCallback<? super R> resultCallback, long j, TimeUnit timeUnit) {
        this.zzaiy.setResultCallback(resultCallback, j, timeUnit);
    }

    public void zza(PendingResult.zza zza) {
        this.zzaiy.zza(zza);
    }

    public Integer zzpa() {
        return this.zzaiy.zzpa();
    }
}
